#+TITLE: Fisymat 
#+SUBTITLE:
#+AUTHOR: Ignacio Cordón Castillo
#+OPTIONS: toc:nil
#+LANGUAGE: es
#+STARTUP: indent
#+DATE:

#+BEGIN_HTML
\(
  \newcommand{\seq}[2]{\{ {#1} \} \rightarrow {#2}}
  \newcommand{\dseq}[3]{\{ {#1} \} \overset{{#3}}{\longrightarrow} {#2}}
\)
#+END_HTML

#+latex_header: \newcommand{\seq}[2]{\{ {#1} \} \rightarrow {#2}}
#+latex_header: \newcommand{\dseq}[3]{\{ {#1} \} \overset{{#3}}{\longrightarrow} {#2}}

#+latex_header: \usepackage{amsmath} 
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{mathabx}
#+latex_header: \newtheorem*{theorem}{Teorema}
#+latex_header: \newtheorem*{fact}{Proposición}
#+latex_header: \newtheorem*{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{color}
#+latex_header: \everymath{\displaystyle}
#+attr_latex: :float t :width 4cm

#+SETUPFILE: ../theme-readtheorg.setup

* Espacios de Hilbert
** Producto escalar
Un producto escalar se define como una aplicación $\langle \cdot, \cdot\rangle: V \rangle V \rightarrow \mathbb{R}$ que verifica:
1. Bilineal
2. Simétrica
3. $\langle u,u\rangle \ge 0, \forall u\in V$ y $\langle u,u\rangle = 0 \Leftrightarrow u = 0$
   
*** Norma asociada al producto escalar
Se verifica, que definiendo $||u|| = \sqrt{\langle u,u\rangle}$, es norma (no negativa, nula sólo para el elemento 0, y saca escalares).

También podemos recuperar el producto escalar a partir de la norma definida a partir de él:

\[\langle u,v\rangle = \frac{1}{4} (||u+v||^2 - ||u-v||^2)\]

1. Desigualdad de Schwarz: $|\langle u,v\rangle| \le ||u|| ||v||$
2. Desigualdad triangular: $||u+v|| \le ||u|| + ||v||$
3. Identidad del paralelogramo: $||u+v||^2 + ||u-v||^2 = 2(||u||^2 + ||v||^2), \quad \forall u,v \in V$

**** Demostración
La demostración de ii es trivial una vez tenemos i. La demostración de iii. consiste en hacer un simple desarrollo de $||u+v||^2$ y $||u-v||^2$.

Veamos i:

\[||u||^2 + 2\lambda \langle u,v\rangle + \lambda^2 ||v||^2 = \langle u+\lambda v, u+\lambda v\rangle \ge 0\]

y tomando $\lambda = -\frac{\langle u,v\rangle}{||v||^2}$ se llega al resultado buscado.
*** Continuidad del producto escalar
Dada $\dseq{w_n}{w}{||\cdot||}$, entonces $\seq{\langle v,w_n\rangle}{\langle v,w\rangle}$.

**** Demostración
Trivial desde Cauchy Schwarz
** Espacio de Hilbert
Dado $V$ espacio vectorial, decimos que es espacio de Hilbert si es completo respecto de la norma inducida por dicho producto escalar.
*** Ejemplos
- $\mathbb{R}^n$ con el producto escalar usual
- $l_2$ espacio de sucesiones tal que $\sum_{n\ge 1} x_n^2$ con $\langle \bar{x}, \bar{y}\rangle = \sum_{n\ge 1} x_n y_n$, $\bar{x} = \{x_n\}$
- $\Omega \subset \mathbb{R}^n$, $L^2(\Omega)$ con el producto escalar $\langle f,g\rangle = \int_{\Omega} fg$

**** Demostración
Veamos una demostración de la afirmación de que $l_2$ es de Hilbert:
*** Suma de espacios Hilbert
La suma directa $H_1 \oplus H_2$ de dos espacios Hilbert $H_1$ y $H_2$ con el producto escalar 

\[\langle u_1 + u_2, v_1 + v_2 \rangle_{H_1 \oplus H_2} = \langle u_1, v_1\rangle_{H_1} + \langle u_2, v_2\rangle_{H_2}\]

Podemos definir la norma asociada como $||u||_{H_1 \oplus H_2} = \sqrt{||u_1||_{H_1}^2 + ||u_2||_{H_2}^2}$ con $u=u_1 + u_2$ y $u_i \in H_i$.

**** Demostración
Sabemos de geometría que $H_1 \oplus H_2$ es espacio vectorial. Veamos que es $\langle \cdot, \cdot \rangle$ definido arriba es producto escalar en $H_1 \oplus H_2$ y que además $H_1 \oplus H_2$ es completo para la norma asociada.

Veamos linealidad en la primera variable: 

\[\begin{align*}
\langle au + bv, w \rangle &= \langle au_1 + b_v1 + au_2 + bv_2, w \rangle = \langle au_1 + bv_1, w_1\rangle_{H_1} + \langle au_2 + bv_2, w_2\rangle_{H_2} = \\
&= a \left[\langle u_1, w_1\rangle_{H_1} + \langle u_2, w_2\rangle_{H_2} \right] + b \left[\langle v_1, w_1\rangle_{H_1} + \langle v_2, w_2\rangle_{H_2} \right] = \\
&= a \langle v_1, w_1 \rangle_{H_1 \oplus H_2} + b \langle v_2, w_2 \rangle_{H_1 \oplus H_2}
\end{align*}\]

La linealidad en la segunda variable es análoga.

Trivialmente $\langle u, u \rangle_{H_1 \oplus H_2} \ge 0$ y la simetría también se deduce de la simetría de los productos escalares en $H_1$ y $H_2$

Veamos que $H_1 \oplus H_2$ es completo.

Sea $\{u_n\} \subset H_1 \oplus H_2$ de Cauchy. Entonces dado $\epsilon > 0$, existe $n\in \mathbb{N}$ tal que para todo $p,q \ge n$:

\[\langle u_p - u_q, u_p - u_q \rangle \le \epsilon \Rightarrow ||(u_i)_p - (u_i)_q||^2 \le \epsilon\]


Esto último implica que $(u_1)_n$ y $(u_2)_n$ son de Cauchy, y por tanto $\seq{(u_i)_n}{u_i}, \quad u_i\in H_i$

Se sigue:

\[||u_n - u||^2 = ||(u_1)_n - u_1||^2 + ||(u_2)_n - u_2||^2 \rightarrow 0\]
