#+TITLE: Fisymat 
#+SUBTITLE:
#+AUTHOR: Ignacio Cordón Castillo
#+OPTIONS: toc:nil
#+LANGUAGE: es
#+STARTUP: indent
#+DATE:

#+BEGIN_HTML
\(
  \newcommand{\seq}[2]{\{ {#1} \} \rightarrow {#2}}
  \newcommand{\weakseq}[2]{\{ {#1} \} \rightharpoonup {#2}}
  \newcommand{\dseq}[3]{\{ {#1} \} \overset{{#3}}{\longrightarrow} {#2}}
  \newcommand{\dotprod}[2]{\langle {#1}, {#2} \rangle}
  \newcommand{\norm}[1]{||{#1}||}
  \newcommand{\abs}[1]{|{#1}|}
  \newcommand{\opspace}[2]{\mathcal{L}({#1}, {#2})}
  \newcommand{\opnorm}[3]{||{#1}||_{\opspace{#2}{#3}}}
  \newcommand{\dual}[1]{\opspace{#1}{\mathbb{R}}}
  \DeclareMathOperator*{\argmin}{arg\,min }
  \DeclareMathOperator*{\argmin}{arg\,max }
\)
#+END_HTML

#+latex_header: \newcommand{\seq}[2]{\{ {#1} \} \rightarrow {#2}}
#+latex_header: \newcommand{\weakseq}[2]{\{ {#1} \} \rightharpoonup {#2}}
#+latex_header: \newcommand{\dseq}[3]{\{ {#1} \} \overset{{#3}}{\longrightarrow} {#2}}
#+latex_header: \newcommand{\dotprod}[2]{\langle {#1}, {#2} \rangle}
#+latex_header: \newcommand{\norm}[1]{||{#1}||}
#+latex_header: \newcommand{\abs}[1]{|{#1}|}
#+latex_header: \newcommand{\opspace}[2]{\mathcal{L}({#1}, {#2})}
#+latex_header: \newcommand{\opnorm}[3]{||{#1}||_{\opspace{#2}{#3}}}
#+latex_header: \newcommand{\dual}[1]{\opspace{#1}{\mathbb{R}}}
#+latex_header: \DeclareMathOperator*{\argmin}{arg\,min }
#+latex_header: \DeclareMathOperator*{\argmin}{arg\,max }
#+latex_header: \usepackage{amsmath} 
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{mathabx}
#+latex_header: \newtheorem*{theorem}{Teorema}
#+latex_header: \newtheorem*{fact}{Proposición}
#+latex_header: \newtheorem*{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{color}
#+latex_header: \everymath{\displaystyle}

#+SETUPFILE: ../theme-readtheorg.setup

* Espacios de Hilbert
** Producto escalar
Un producto escalar se define como una aplicación $\langle \cdot, \cdot\rangle: V \rangle V \rightarrow \mathbb{R}$ que verifica:
1. Bilineal
2. Simétrica
3. $\langle u,u\rangle \ge 0, \forall u\in V$ y $\langle u,u\rangle = 0 \Leftrightarrow u = 0$
   
*** Norma asociada al producto escalar
Se verifica, que definiendo $||u|| = \sqrt{\langle u,u\rangle}$, es norma (no negativa, nula sólo para el elemento 0, y saca escalares).

También podemos recuperar el producto escalar a partir de la norma definida a partir de él:

\[\langle u,v\rangle = \frac{1}{4} (||u+v||^2 - ||u-v||^2)\]

1. Desigualdad de Schwarz: $|\langle u,v\rangle| \le ||u|| ||v||$
2. Desigualdad triangular: $||u+v|| \le ||u|| + ||v||$
3. Identidad del paralelogramo: $||u+v||^2 + ||u-v||^2 = 2(||u||^2 + ||v||^2), \quad \forall u,v \in V$

**** Demostración
La demostración de ii es trivial una vez tenemos i. La demostración de iii. consiste en hacer un simple desarrollo de $||u+v||^2$ y $||u-v||^2$.

Veamos i:

\[||u||^2 + 2\lambda \langle u,v\rangle + \lambda^2 ||v||^2 = \langle u+\lambda v, u+\lambda v\rangle \ge 0\]

y tomando $\lambda = -\frac{\langle u,v\rangle}{||v||^2}$ se llega al resultado buscado.
*** Continuidad del producto escalar label:fact:dotcont
Dada $\dseq{w_n}{w}{||\cdot||}$, entonces $\seq{\langle v,w_n\rangle}{\langle v,w\rangle}$.

**** Demostración
Trivial desde Cauchy Schwarz
** Espacio de Hilbert
Dado $V$ espacio vectorial, decimos que es espacio de Hilbert si es completo respecto de la norma inducida por dicho producto escalar.
*** Ejemplos
- $\mathbb{R}^n$ con el producto escalar usual
- $l_2$ espacio de sucesiones tal que $\sum_{n\ge 1} x_n^2$ con $\langle \bar{x}, \bar{y}\rangle = \sum_{n\ge 1} x_n y_n$, $\bar{x} = \{x_n\}$
- $\Omega \subset \mathbb{R}^n$, $L^2(\Omega)$ con el producto escalar $\langle f,g\rangle = \int_{\Omega} fg$

**** Demostración
Veamos una demostración de la afirmación de que $l_2$ es de Hilbert:
*** Suma de espacios Hilbert
La suma directa $H_1 \oplus H_2$ de dos espacios Hilbert $H_1$ y $H_2$ con el producto escalar 

\[\langle u_1 + u_2, v_1 + v_2 \rangle_{H_1 \oplus H_2} = \langle u_1, v_1\rangle_{H_1} + \langle u_2, v_2\rangle_{H_2}\]

Podemos definir la norma asociada como $||u||_{H_1 \oplus H_2} = \sqrt{||u_1||_{H_1}^2 + ||u_2||_{H_2}^2}$ con $u=u_1 + u_2$ y $u_i \in H_i$.

**** Demostración
Sabemos de geometría que $H_1 \oplus H_2$ es espacio vectorial. Veamos que es $\langle \cdot, \cdot \rangle$ definido arriba es producto escalar en $H_1 \oplus H_2$ y que además $H_1 \oplus H_2$ es completo para la norma asociada.

Veamos linealidad en la primera variable: 

\[\begin{align*}
\langle au + bv, w \rangle &= \langle au_1 + b_v1 + au_2 + bv_2, w \rangle = \langle au_1 + bv_1, w_1\rangle_{H_1} + \langle au_2 + bv_2, w_2\rangle_{H_2} = \\
&= a \left[\langle u_1, w_1\rangle_{H_1} + \langle u_2, w_2\rangle_{H_2} \right] + b \left[\langle v_1, w_1\rangle_{H_1} + \langle v_2, w_2\rangle_{H_2} \right] = \\
&= a \langle v_1, w_1 \rangle_{H_1 \oplus H_2} + b \langle v_2, w_2 \rangle_{H_1 \oplus H_2}
\end{align*}\]

La linealidad en la segunda variable es análoga.

Trivialmente $\langle u, u \rangle_{H_1 \oplus H_2} \ge 0$ y la simetría también se deduce de la simetría de los productos escalares en $H_1$ y $H_2$

Veamos que $H_1 \oplus H_2$ es completo.

Sea $\{u_n\} \subset H_1 \oplus H_2$ de Cauchy. Entonces dado $\epsilon > 0$, existe $n\in \mathbb{N}$ tal que para todo $p,q \ge n$:

\[\langle u_p - u_q, u_p - u_q \rangle \le \epsilon \Rightarrow ||(u_i)_p - (u_i)_q||^2 \le \epsilon\]


Esto último implica que $(u_1)_n$ y $(u_2)_n$ son de Cauchy, y por tanto $\seq{(u_i)_n}{u_i}, \quad u_i\in H_i$

Se sigue:

\[||u_n - u||^2 = ||(u_1)_n - u_1||^2 + ||(u_2)_n - u_2||^2 \rightarrow 0\]
** Complemento ortogonal
Sea $V \subseteq H$ sub. vectorial, $H$ espacio Hilbert, entonces se define el *espacio ortogonal* de $V$ como:

\[V^\perp:= \{w\in H : \langle w,v \rangle = 0 \forall v\in V\}\]

Claramente $V^\perp$ es sub vectorial de $H$ y además $V\subseteq (V^\perp)^\perp$. En $\mathbb{R}^n$, $V = (V^\perp)^\perp$, pero en espacios de Hilbert arbitrarios no tiene por qué cumplirse. Como veremos, que $V$ sea cerrado es condición necesaria por ref:fact-cerrado-hilbert y suficiente por ref:th:complemento

Más adelante definiremos el *complemento ortogonal* exigiéndole a un espacio ortogonal que sea lo suficientemente "bueno" para que $V \oplus V^\perp = H$

Sea $V\subseteq H$ sub. vectorial de $H$ Hilbert en lo que sigue.
*** Un espacio ortogonal es cerrado en un Hilbert label:fact:cerrado-hilbert
Dado $V\subseteq H$ sub. vectorial, entonces $V^\perp$ es cerrado.

**** Demostración
Sea $\{w_n\} \subseteq V$ con $\seq{w_n}{w \in H}$

Entonces $0 = \lim_n \dotprod{w_n}{v} = \dotprod{w}{v}$ para cualquier $v \in V$. Luego $w\in V^\perp$

*** Caracterización del ortogonal label:claim:ortogonal
Sea $w\in H$. Entonces:
\[w\in V^\perp \Leftrightarrow ||w|| = \inf_{v\in V}||w-v||\]

**** Demostración
***** Hacia la derecha
\[\dotprod{w-v}{w-v} = \dotprod{w}{w} - 2\dotprod{w}{v} + \dotprod{v}{v} = \dotprod{w}{w} + \dotprod{v}{v} \ge ||w||^2\]

Y tomando $v=0\in V$ terminamos
***** Hacia la izquierda
Fijamos un $v\in V$ y tomamos $f_v : \mathbb{R} \rightarrow \mathbb{R}$ definida por $f_v(t) = \dotprod{w-tv}{w-tv}$.

Por hipótesis $f_v(t) \ge f_v(0)$, pero $f_v'(t) = -2\dotprod{v}{w-tv} = 0$ sii $\frac{\dotprod{v}{w}}{||v||^2} = t$

*** La distancia a un Hilbert se materializa label:fact:dist
Sea $u\in H$, entonces existe un único $v\in V$ verificando $||u-v|| = \inf_{w\in V} ||u-w||$

**** Demostración
Llamamos $L=\inf_{w\in V} ||u-w||$. Podemos tomar $\{v_n\} \in H$ verificándose $\seq{||u-v_n||}{L}$. Basta ver que $\{v_n\}$ es de Cauchy.


\[\begin{align}
\dotprod{w_p - w_q}{w_p - w_q} &= \dotprod{(w_p-u) - (w_q-u)}{(w_p-u) - (w_q-u)} = \\ 
&= ||w_p-u||^2 + ||w_q-u||^2 - 2\dotprod{w_p-u}{w_q-u} = \\
&= ||w_p-u||^2 + ||w_q-u||^2 - 2\dotprod{w_p-u}{w_p - w_p + w_q-u} = \\
&= ||w_p-u||^2 + ||w_q-u||^2 - 2||w_p-u||^2 - 2\dotprod{w_p-u}{w_q - w_p} \le \\
&\le (||w_p-u||^2 + L) + (||w_q-u||^2 + L) - 2(||w_p-u||^2 +L) + 2||w_p-u||||w_q - w_p||
\end{align}\]

Y usando la convergencia $\seq{||u-v_n||}{L}$ y que $\{v_n\}$ es de Cauchay, llegamos al resultado buscado.

Por tanto $\seq{v_n}{v} \in H$, y usando que $V$ es cerrado, $v\in V$, y ello prueba la existencia. Veamos la unicidad: sea otro $\bar{v} \in V$ materializando la distancia:

\[\begin{align}
\norm{v-\bar{v}}^2 &= \norm{v-u -(\bar{v}-u)}^2 \underset{(*)}{=} 2(\norm{v-u}^2 + \norm{\bar{v}-u}^2) - \norm{v+\bar{v}-2u}^2 = \\
&= 2L^2 - 2\norm{\frac{v+\bar{v}}{2} - u} \le 2L^2 - 2L^2 = 0
\end{align}\]

donde se ha usado la identidad del paralelogramo en (*).
*** Proyección ortogonal (de $H$ sobre $V$) label:claim:proy
A partir de ref:fact:dist podemos definir la proyección ortogonal como:

Se define como $p_V: H \rightarrow V$ dada por $p_V(u) = \argmin_{v\in V} \norm{u-v}$

**** Caracterización de $p_V$
Si $V$ es sub.cerrado de $H$ y $u\in H$ entonces $p_V(u)$ es el único elemento de $V$ verificando $u-p_V(u) \in V^\perp$

***** Demostración
La existencia es trivial a partir de label:claim:ortogonal y el hecho de que $p_V(u)$ minimiza la distancia de $u$ a $V$. 

\[u-p_V(u) \in V^\perp \Leftrightarrow \norm{u-p_V(u)} = \inf_{w\in V} \norm{u-p_V(u) - w}\]

Pero $\inf_{w\in V} \norm{u-p_V(u) - w} = \inf_{w\in V} \norm{u-w}$ y se cumple lo anterior por la definición de $p_V(u)$.

La unicidad viene dada por ref:fact:dist
*** Complemento ortogonal label:th:complemento
Decimos que $V^\perp$ es complemento ortogonal de $V$ en $H$ si $V\oplus V^\perp = H$

Nótese que si un espacio no es cerrado, no podríamos definir la proyección, y el siguiente teorema no sería válido.
 
**** Teorema del complemento ortogonal
Sea $V$ subespacio vectorial cerrado de $H$. Se cumple:

1. $p_V$ es la única aplicación lineal en $V^H$ verificando que $p_V \circ p_V = p_V$ y $Ker p_V = V^\perp$
2. $p_V$ es continua y $\opnorm{p_V}{H}{V} = 1$ si $V\neq \emptyset$
3. $i:V \oplus V^\perp \hookrightarrow H$ es isometría lineal.


Recordamos que la norma de operadores se define como $\opnorm{T}{V}{W} = \sup_{v\in V, \, \norm{v}_V = 1} \norm{T(v)}_W$, donde $\opspace{V}{W} = \{h:V\rightarrow W$ continua y lineal$\}$

***** Demostración
****** Primer punto
$p_V \circ p_V = p_V$ es trivial

$Ker p_V = V^\perp$, ya que dado $x\in H, p_V(x)=0$, tenemos $0 = p_V(x) = \argmin_{w\in V} \norm{w-x}$, sii $\norm{x} = \min_{w\in V} \norm{w-x}$. Por último: ref:claim:ortogonal nos dice que lo anterior se cumple sii $x\in V^\perp$

$p_V$ es lineal, porque por ref:claim:proy, como $\lambda u + \mu w - \lambda p_V(u) + \mu p_V(w) = \lambda (u-p_V(u)) + \mu (w-p_V(w)) \in V^\perp$, entonces $p_V(\lambda u + \mu w) = \lambda p_V(u) + \mu p_V(w)$.

Es la única aplicación lineal que cumple eso porque dada $f$ lineal verificando ambas condiciones, entonces:

\[f(f(x)-x) = f(f(x)) - f(x) \underset{f\circ f=f}{=} f(x) - f(x) = 0\]

Luego $f(x) - x \in V^\perp$ sii, por ref:claim:ortogonal $\norm{f(x)-x} = \inf_{w \in V} \norm{f(x) - x - w} \underset{f(x) \in V}{=} \inf_{w \in V} \norm{x-w}$, luego como por ser $V$ cerrado existe un único elemento que materializa la distancia, por label:fact:dist  entonces $f(x) = p_V(x)$
****** Segundo punto
Escribimos $u = u - p_V(u) + p_V(u)$, donde sabemos $u - p_V(u) \in V^\perp$, luego: 

\[\dotprod{u}{u-p_V(u)} = \norm{u}^2 - \dotprod{u}{p_V(u)} = \norm{u-p_V(u)}^2\]

Es decir:

\[\norm{u}^2 - \dotprod{u-p_V(u) + p_V(u)}{p_V(u)} = \norm{u}^2 - \norm{p_V(u)}^2 = \norm{u-p_V(u)}^2\]

Y se deduce $\norm{p_V(u)} \le \norm{u}$, y de aquí $\opnorm{p_V}{H}{V} \le 1$. Esto nos da continuidad.

Si $V \neq 0$, tomando $v\in V$, $p_V\left(\frac{v}{\norm{v}}\right) = \frac{v}{\norm{v}}$ y por tanto $\opnorm{p_V}{H}{V} = 1$
****** Tercer punto
Es claramente una función lineal, de kernel nulo, luego inyectiva, y es biyectiva, ya que dado $y\in H$, $i((y - p_V(y)) + p_V(y)) = y$, luego es isomorfismo lineal.

Es isometría por ser $\norm{u+v}_H^2 = ||u||^2 + ||v||^2 = \norm{u+v}_{V\oplus V^\perp}^2$, para $u\in V, v\in V^\perp$.



** Teorema de representación de Riesz-Fréchet
Sea $H$ espacio Hilbert
*** Dual topológico de $H$
Llamamos dual topológico de $H$ a $\dual{H}$.
*** Funciones del dual descritas por un producto escalar
Dado $w\in H$, la función de $\dual{H}$ dada por $T_w(v):=\dotprod{w}{v}$ es lineal, continua, y de norma $\norm{w}_H$

**** Demostración
Que es lineal y continua es claro por la linealidad y la continuidad del producto escalar, demostrada en ref:fact:dotcont

\[|T_w(v)| = |\dotprod{w}{v}| \le \norm{w}\norm{v}\] 

por Cauchy Schwarz, luego $\opnorm{T_w}{H}{\mathbb{R}} \le \norm{w}$ y para ver que es de hecho $\norm{w}$ basta evaluar en $\frac{w}{\norm{w}}$ si $w\neq 0$.
*** Principio de Dirichlet
Sea $V$ espacio vectorial con un producto escalar $\dotprod{\cdot}{\cdot}$, $T\in \opspace{V}{\mathbb{R}$. 
Entonces $T = T_w = \dotprod{w}{\cdot}$ sii $w\in V$ es mínimo del funcional $J(u) = \frac{1}{2} \norm{u}^2 - T(u)$

**** Demostración
***** Hacia la derecha
Por desigualdad de Cauchy-Schwarz: $J(u) = \frac{1}{2} \norm{u}^2 - \dotprod{w}{u} \ge \frac{1}{2} \norm{u}^2 - \norm{w}\norm{u}$

Y el polinomio $\frac{1}{2}x^2 - \norm{w}x$ tiene un mínimo en $\norm{u} = x = \norm{w}$, pero la desigualdad anterior es estricta
sii $u = tw, t\ge 0$. Juntando estas dos condiciones $u = w$
***** Hacia la izquierda
Fijo $u\in V$ arbitrario y llamo $J_u(t) = J(w+tu) = \frac{1}{2}\dotprod{w+tu}{w+tu} - T(w) - tT(u) \ge J(w)$.

Su derivada es $J_u'(t) = \dotprod{u}{w+tu} - T(u)$ y esta función tiene un mínimo en $0$, luego:

\[J_u'(0) = 0 = \dotprod{u}{w} - T(u)\]

*** Teorema de representación de Riesz-Fréchet label:th:rieszfrechet
Sea $H$ espacio de Hilbert y $T\in \dual{H}$ (espacio de funciones lineales y continuas de $H$ a $\mathbb{R}$).
Entonces existe un único $w\in H$ verificando:

\[T(u) = T_w(u)\]

De hecho la aplicación $i: H \hookrightarrow \dual{H}$ dada por $i(w) = T_w$ es isomorfismo lineal e isometría.

**** Demostración
Supongamos que se cumplen las primeras hipótesis, y veamos que $i$ es isometría.

\[i(\lambda v + \mu w) (u) = \dotprod{\lambda v + \mu w}{u} = \lambda\dotprod{v}{u} + \mu\dotprod{w}{u} = (\lambda T_v + \mu T_w) (u)\]

Esto prueba que $i$ es lineal, y las primeras hipótesis que $i$ es biyectiva (hay un único $w\in H$ para cada $T\in \dual{H}$


Usamos el principio de Dirichlet para demostrar la primera parte del teorema. Basta ver que $J(u) = \frac{1}{2} \norm{u}^2 - T(u)$ siempre tiene un mínimo.

Sea $w_0 = \arg max_{u\in H, \norm{u}=1} T(u)$

Entonces:

\[J(u) = \frac{1}{2} \norm{u}^2 - \norm{u} T(\frac{u}{\norm{u}}) \ge \frac{1}{2} \norm{u}^2 - \norm{u} T(w_0)\]

Y el polinomio $\frac{1}{2}x^2-T(w_0)x$ tiene su mínimo en $x=\norm{u} = T(w_0)$

Es decir, tomando $u=T(w_0)w_0$ llegamos al resultado buscado.

La unicidad del representante se tiene porque dados $w,\bar{w} \in H$ verificando $T(u) = \dotprod{w}{u} = \dotprod{\bar{w}}{u}$ para todo $u\in H$, se tiene $\dotprod{w-\bar{w}}{u} = 0$ para todo $u\in H$, en particular para $u=w-\bar{w}$, lo que implica que $\norm{w-\bar{w}} = 0$ y $w=\bar{w}$
** Bases de Hilbert
Sea $H$ espacio Hilbert
*** Subespacio lineal generado por $X$
Sea $X\subseteq H$, denotamos por $lin X:= \left\{\sum_{i=1}^m \alpha_i v_i : \alpha_i\in \mathbb{R}, v_i \in X, m\in \mathbb{N}\right\}$
*** Subconjunto ortogonal
Sea $O\subseteq H$. $O$ es conjunto ortogonal sii $\dotprod{u,v} = 0$ para todos $u,v \in O$, con $u\neq v$.

Decimos que $O$ es ortonormal si es ortogonal y $\norm{u} = 1$ para todo $u\in V$
*** Base de Hilbert
$B\subseteq H$ se dice base de Hilbert de $H$ si es ortonormal y $H = \widebar{lin B}$

**** Base de Hilbert vs base algebraica
El concepto de base de Hilbert y de base algebraica no coincide. Ej: El conjunto formado por las sucesiones $(x_n)_k := \delta_{k,n}$ donde $\delta_{k,n}$ es la delta de Dirac, es base de Hilbert de $l_2$, pero no es base algebraica.
** Convergencia débil
Sea $H$ espacio de Hilbert
*** Definición de convergencia débil
Una sucesión $\{x_n\}_n$ en $H$ se dice que converge débilmente a $u\in H$ si para cada $v\in H$ se verifica:

\[\lim_{n} \dotprod{x_n}{v} = \dotprod{u}{v}\]

Lo notamos $\weakseq{x_n}{u}$ y decimos que $u$ es el límite débil de $\{x_n\}$

Además dicho límite, caso de existir, es único

**** Demostración (unicidad del límite)
Sean $u, \bar{u}$ dos límites distintos. Entonces para todo $v \in H$ se tiene:

\[0 = \lim_{n} \dotprod{x_n}{v} - \lim_{n} \dotprod{x_n}{v} = \dotprod{u}{v} - \dotprod{\bar{u}}{v} = \dotprod{u-\bar{u}}{v}\]

En particular $\dotprod{u-\bar{u}}{u-\bar{u}} = 0$, y por tanto $u = \bar{u}$
*** Convergencia fuerte (convencional) implica convergencia débil
Sea $\{x_n\}$ sucesión en $H$ verificando $\seq{x_n}{x \in H}$. Entonces $\weakseq{x_n}{x}$
**** Demostración
\[\dotprod{x_n}{v} - \dotprod{x}{v} = \dotprod{x_n - x}{v} \overset{n\rightarrow \infty} \rightarrow 0\]

donde se ha usado continuidad del producto escalar.
**** El recíproco no es cierto
Sea un espacio de dimensión infinita, $H$ y una base ortogonal $B$. Entonces tomando una sucesión $\{u_n\} \subseteq B$ y llamamos $e_n = \frac{u_n}{\norm{u_n}}$, se tiene que fijado $v\in H$, $\dotprod{e_n}{v} = 0$ para $n \ge 1$ suficientemente grande, ya que $v= \sum_{i=1}^N \alpha_i v_i$ con $v_i\in B$ por ser $B$ base y $B$ es ortonormal, de donde se desprende la afirmación que hemos hecho.

Hemos probado que $\weakseq{x_n}{0}$, pero $\norm{e_n}=1$ para todo $n$, luego no hay convergencia fuerte a $0$.
*** Condiciones suficientes para que convergencia débil implique convergencia fuerte
Se cumple:

1. Si $\weakseq{u_n}{u \in H}$ entonces $\norm{u} \le \liminf_{n} \norm{u_n}$
2. Si $\weakseq{u_n}{u \in H}$ entonces $\seq{u_n}{u}$ sii $\seq{\norm{u_n}}{\norm{u}}$

**** Demostración
***** Primer apartado
$\dotprod{u_n}{u} \le \norm{u_n} \norm{u}$ y tomando $\liminf_{n}$ en ambos miembros llegamos al resultado buscado.
***** Segundo apartado
Hacia la izquierda es evidente. Vemos hacia la derecha:

\[\dotprod{u_n - u}{u_n - u} = \norm{u_n}^2 - 2\dotprod{u_n}{u} + \norm{u}^2\]

De donde tomando límites en $n$ llegamos a $\seq{\norm{u_n-u}^2}{0}$

*** Condiciones suficientes para que haya convergencia débil
Sea $\{u_n\}$ sucesión acotada en $H$ verificando que $\{\dotprod{u_n}{v}\}$ converge en $\mathbb{R}$ para cualquier $v\in H$. Entonces existe $u\in H$ verificando $\weakseq{u_n}{u}$

label:lemma:weakconv
**** Demostración
Definimos $T:H\rightarrow \mathbb{R}$ por $T(v) = \lim_n \dotprod{u_n}{u}$.

$T$ es lineal, y continua porque dado $v\in H, \norm{v}=1$ entonces $|T(v)| = \lim_n \dotprod{u_n}{u} \le \alpha$ donde $\alpha$ es una cota para cualquier $\norm{u_n}$.

Luego $T$ es continua, y por teorema de Riesz-Fréchet ref:th:rieszfrechet existe $u\in H$, y $T(v) = \dotprod{u}{v}$.
*** Propiedad fundamental de convergencia débil
Sea una sucesión acotada en $H$. Entonces contiene una subsucesión débilmente convergente en $H$.

**** Demostración
Sea $\{u_n\} \subseteq H$ verificando $\norm{u_n}\le \alpha$ para todo $n\ge 1$. Si $\alpha = 0$, $u_n=0$ para todo $n$ y ya tendríamos el resultado. Supongamos $\alpha\neq 0$. Entonces $\dotprod{u_n}{u_1} \le \alpha \norm{u_1}$ y existe una parcial de $\{u_n\}$, que llamamos $\{u_n^{(1)}\}$ que hace $\dotprod{u_n^{(1)}}{u_1}$ converja.

Recursivamente, podemos definir $\{u_n^{(k)}\}$ como la parcial de $\{u_n^{(k-1)}\}$ que hace que $\dotprod{u_n^{(k)}}{u_{k-1}}$ converja.

Definimos la sucesión $w_n = u_n^{(n)}$ (el elemento $n$-ésimo de la parcial $n$-ésima)

Veamos que $\dotprod{w_n}{v}$ converge para todo $v\in H$.

Si $v = u_m$ para algún $m$, entonces $\dotprod{u_n^{(m)}}{u_m}$ converge en $n$, y por tanto, $\dotprod{w_m}{u_m}$ también, por ser $\{w_{n+m}\}$ una subsucesión de $\{u_n^{(m)}\}$, luego $\dotprod{w_n}{v}$ converge.

Si $v \in V:=lin\{u_n : n\in\mathbb{N}\}$ entonces por un argumento similar tendríamos que $\dotprod{w_n}{v}$ converge.

Si $v \in \bar{V}$, tomamos $y\in V$ con $\norm{v-y} \le \frac{\epsilon}{4\alpha}$. Como $y\in V$, tenemos que existe $m\in\mathbb{N}$ tal que para todo $p,q \ge m$, $|\dotprod{w_p -w_q}{y}| \le \epsilon$. Vamos a ver que $\dotprod{w_n}{v}$ es de Cauchy en $\mathbb{R}$, luego convergente por ser $\mathbb{R}$ espacio Banach. 

Así:

\begin{align}
\abs{\dotprod{w_p - w_q}{v}} &= \abs{\dotprod{w_p-w_q}{v-y+y}} = 
                              \abs{\dotprod{w_p-w_q}{v-y} + \dotprod{w_p-w_q}{y}}\le \\ 
                              &\le (\norm{w_p}+\norm{w_q})\abs{v-y} + \frac{\epsilon}{2} 
                              \le 2\alpha \cdot \frac{\epsilon}{4\alpha} + 
                              \frac{\epsilon}{2}\le \epsilon
\end{align}

Como $H$ es de Hilbert, $\bar{V}\oplus \bar{V}^\perp = H$, y dado $v\in H$ arbitrario, $v = a+b$ con $a\in \bar{V}$ y $b\in \bar{V}^\perp$. Luego:

\[\dotprod{w_n}{v} = \dotprod{w_n}{a} + \dotprod{w_n}{b} = \dotprod{w_n}{a}\]

Por ser $b\in \bar{V}^\perp$ y $w_n\in V$. Y hemos probado que $\dotprod{w_n}{a}$ converge.

Estamos en condiciones de aplicar ref:lemma:weakconv

