#+TITLE: Fisymat 
#+SUBTITLE:
#+AUTHOR: Ignacio Cordón Castillo
#+OPTIONS: toc:nil
#+LANGUAGE: es
#+STARTUP: indent
#+DATE:

#+BEGIN_HTML
\(
  \newcommand{\seq}[2]{\{ {#1} \} \rightarrow {#2}}
  \newcommand{\dseq}[3]{\{ {#1} \} \overset{{#3}}{\longrightarrow} {#2}}
  \newcommand{\dotprod}[2]{\langle {#1}, \rangle {#2} \rangle}
  \newcommand{\norm}[1]{||{#1}||}
  \newcommand{\opnorm}[3]{||{#1}||_{\mathcal{L}({#2}, {#3})}}
  \DeclareMathOperator*{\argmin}{arg\,min }
\)
#+END_HTML

#+latex_header: \newcommand{\seq}[2]{\{ {#1} \} \rightarrow {#2}}
#+latex_header: \newcommand{\dseq}[3]{\{ {#1} \} \overset{{#3}}{\longrightarrow} {#2}}
#+latex_header: \newcommand{\dotprod}[2]{\langle {#1}, {#2} \rangle}
#+latex_header: \newcommand{\norm}[1]{||{#1}||}
#+latex_header: \newcommand{\opspace}[2]{\mathcal{L}({#1}, {#2})}
#+latex_header: \newcommand{\opnorm}[3]{||{#1}||_{\opspace{#2}{#3}}}
#+latex_header: \DeclareMathOperator*{\argmin}{arg\,min }
#+latex_header: \usepackage{amsmath} 
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage{mathabx}
#+latex_header: \newtheorem*{theorem}{Teorema}
#+latex_header: \newtheorem*{fact}{Proposición}
#+latex_header: \newtheorem*{definition}{Definición}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{color}
#+latex_header: \everymath{\displaystyle}

#+SETUPFILE: ../theme-readtheorg.setup

* Espacios de Hilbert
** Producto escalar
Un producto escalar se define como una aplicación $\langle \cdot, \cdot\rangle: V \rangle V \rightarrow \mathbb{R}$ que verifica:
1. Bilineal
2. Simétrica
3. $\langle u,u\rangle \ge 0, \forall u\in V$ y $\langle u,u\rangle = 0 \Leftrightarrow u = 0$
   
*** Norma asociada al producto escalar
Se verifica, que definiendo $||u|| = \sqrt{\langle u,u\rangle}$, es norma (no negativa, nula sólo para el elemento 0, y saca escalares).

También podemos recuperar el producto escalar a partir de la norma definida a partir de él:

\[\langle u,v\rangle = \frac{1}{4} (||u+v||^2 - ||u-v||^2)\]

1. Desigualdad de Schwarz: $|\langle u,v\rangle| \le ||u|| ||v||$
2. Desigualdad triangular: $||u+v|| \le ||u|| + ||v||$
3. Identidad del paralelogramo: $||u+v||^2 + ||u-v||^2 = 2(||u||^2 + ||v||^2), \quad \forall u,v \in V$

**** Demostración
La demostración de ii es trivial una vez tenemos i. La demostración de iii. consiste en hacer un simple desarrollo de $||u+v||^2$ y $||u-v||^2$.

Veamos i:

\[||u||^2 + 2\lambda \langle u,v\rangle + \lambda^2 ||v||^2 = \langle u+\lambda v, u+\lambda v\rangle \ge 0\]

y tomando $\lambda = -\frac{\langle u,v\rangle}{||v||^2}$ se llega al resultado buscado.
*** Continuidad del producto escalar
Dada $\dseq{w_n}{w}{||\cdot||}$, entonces $\seq{\langle v,w_n\rangle}{\langle v,w\rangle}$.

**** Demostración
Trivial desde Cauchy Schwarz
** Espacio de Hilbert
Dado $V$ espacio vectorial, decimos que es espacio de Hilbert si es completo respecto de la norma inducida por dicho producto escalar.
*** Ejemplos
- $\mathbb{R}^n$ con el producto escalar usual
- $l_2$ espacio de sucesiones tal que $\sum_{n\ge 1} x_n^2$ con $\langle \bar{x}, \bar{y}\rangle = \sum_{n\ge 1} x_n y_n$, $\bar{x} = \{x_n\}$
- $\Omega \subset \mathbb{R}^n$, $L^2(\Omega)$ con el producto escalar $\langle f,g\rangle = \int_{\Omega} fg$

**** Demostración
Veamos una demostración de la afirmación de que $l_2$ es de Hilbert:
*** Suma de espacios Hilbert
La suma directa $H_1 \oplus H_2$ de dos espacios Hilbert $H_1$ y $H_2$ con el producto escalar 

\[\langle u_1 + u_2, v_1 + v_2 \rangle_{H_1 \oplus H_2} = \langle u_1, v_1\rangle_{H_1} + \langle u_2, v_2\rangle_{H_2}\]

Podemos definir la norma asociada como $||u||_{H_1 \oplus H_2} = \sqrt{||u_1||_{H_1}^2 + ||u_2||_{H_2}^2}$ con $u=u_1 + u_2$ y $u_i \in H_i$.

**** Demostración
Sabemos de geometría que $H_1 \oplus H_2$ es espacio vectorial. Veamos que es $\langle \cdot, \cdot \rangle$ definido arriba es producto escalar en $H_1 \oplus H_2$ y que además $H_1 \oplus H_2$ es completo para la norma asociada.

Veamos linealidad en la primera variable: 

\[\begin{align*}
\langle au + bv, w \rangle &= \langle au_1 + b_v1 + au_2 + bv_2, w \rangle = \langle au_1 + bv_1, w_1\rangle_{H_1} + \langle au_2 + bv_2, w_2\rangle_{H_2} = \\
&= a \left[\langle u_1, w_1\rangle_{H_1} + \langle u_2, w_2\rangle_{H_2} \right] + b \left[\langle v_1, w_1\rangle_{H_1} + \langle v_2, w_2\rangle_{H_2} \right] = \\
&= a \langle v_1, w_1 \rangle_{H_1 \oplus H_2} + b \langle v_2, w_2 \rangle_{H_1 \oplus H_2}
\end{align*}\]

La linealidad en la segunda variable es análoga.

Trivialmente $\langle u, u \rangle_{H_1 \oplus H_2} \ge 0$ y la simetría también se deduce de la simetría de los productos escalares en $H_1$ y $H_2$

Veamos que $H_1 \oplus H_2$ es completo.

Sea $\{u_n\} \subset H_1 \oplus H_2$ de Cauchy. Entonces dado $\epsilon > 0$, existe $n\in \mathbb{N}$ tal que para todo $p,q \ge n$:

\[\langle u_p - u_q, u_p - u_q \rangle \le \epsilon \Rightarrow ||(u_i)_p - (u_i)_q||^2 \le \epsilon\]


Esto último implica que $(u_1)_n$ y $(u_2)_n$ son de Cauchy, y por tanto $\seq{(u_i)_n}{u_i}, \quad u_i\in H_i$

Se sigue:

\[||u_n - u||^2 = ||(u_1)_n - u_1||^2 + ||(u_2)_n - u_2||^2 \rightarrow 0\]
** Complemento ortogonal
Sea $V \subseteq H$ sub. vectorial, $H$ espacio Hilbert, entonces se define el *espacio ortogonal* de $V$ como:

\[V^\perp:= \{w\in H : \langle w,v \rangle = 0 \forall v\in V\}\]

Claramente $V^\perp$ es sub vectorial de $H$ y además $V\subseteq (V^\perp)^\perp$. En $\mathbb{R}^n$, $V = (V^\perp)^\perp$, pero en espacios de Hilbert arbitrarios no tiene por qué cumplirse. Como veremos, que $V$ sea cerrado es condición necesaria por ref:claim-cerrado y suficiente por ref:th:complemento

Más adelante definiremos el *complemento ortogonal* exigiéndole a un espacio ortogonal que sea lo suficientemente "bueno" para que $V \oplus V^\perp = H$

Sea $V\subseteq H$ sub. vectorial de $H$ Hilbert en lo que sigue.
*** Un espacio ortogonal es cerrado en un Hilbert label:claim-cerrado
Dado $V\subseteq H$ sub. vectorial, entonces $V^\perp$ es cerrado.

**** Demostración
Sea $\{w_n\} \subseteq V$ con $\seq{w_n}{w \in H}$

Entonces $0 = \lim_n \dotprod{w_n}{v} = \dotprod{w}{v}$ para cualquier $v \in V$. Luego $w\in V^\perp$

*** Caracterización del ortogonal label:claim:ortogonal
Sea $w\in H$. Entonces:
\[w\in V^\perp \Leftrightarrow ||w|| = \inf_{v\in V}||w-v||\]

**** Demostración
***** Hacia la derecha
\[\dotprod{w-v}{w-v} = \dotprod{w}{w} - 2\dotprod{w}{v} + \dotprod{v}{v} = \dotprod{w}{w} + \dotprod{v}{v} \ge ||w||^2\]

Y tomando $v=0\in V$ terminamos
***** Hacia la izquierda
Fijamos un $v\in V$ y tomamos $f_v : \mathbb{R} \rightarrow \mathbb{R}$ definida por $f_v(t) = \dotprod{w-tv}{w-tv}$.

Por hipótesis $f_v(t) \ge f_v(0)$, pero $f_v'(t) = -2\dotprod{v}{w-tv} = 0$ sii $\frac{\dotprod{v}{w}}{||v||^2} = t$

*** La distancia a un Hilbert se materializa label:fact:dist
Sea $u\in H$, entonces existe un único $v\in V$ verificando $||u-v|| = \inf_{w\in V} ||u-w||$

**** Demostración
Llamamos $L=\inf_{w\in V} ||u-w||$. Podemos tomar $\{v_n\} \in H$ verificándose $\seq{||u-v_n||}{L}$. Basta ver que $\{v_n\}$ es de Cauchy.


\[\begin{align}
\dotprod{w_p - w_q}{w_p - w_q} &= \dotprod{(w_p-u) - (w_q-u)}{(w_p-u) - (w_q-u)} = \\ 
&= ||w_p-u||^2 + ||w_q-u||^2 - 2\dotprod{w_p-u}{w_q-u} = \\
&= ||w_p-u||^2 + ||w_q-u||^2 - 2\dotprod{w_p-u}{w_p - w_p + w_q-u} = \\
&= ||w_p-u||^2 + ||w_q-u||^2 - 2||w_p-u||^2 - 2\dotprod{w_p-u}{w_q - w_p} \le \\
&\le (||w_p-u||^2 + L) + (||w_q-u||^2 + L) - 2(||w_p-u||^2 +L) + 2||w_p-u||||w_q - w_p||
\end{align}\]

Y usando la convergencia $\seq{||u-v_n||}{L}$ y que $\{v_n\}$ es de Cauchay, llegamos al resultado buscado.

Por tanto $\seq{v_n}{v} \in H$, y usando que $V$ es cerrado, $v\in V$, y ello prueba la existencia. Veamos la unicidad: sea otro $\bar{v} \in V$ materializando la distancia:

\[\begin{align}
\norm{v-\bar{v}}^2 &= \norm{v-u -(\bar{v}-u)}^2 \underset{(*)}{=} 2(\norm{v-u}^2 + \norm{\bar{v}-u}^2) - \norm{v+\bar{v}-2u}^2 = \\
&= 2L^2 - 2\norm{\frac{v+\bar{v}}{2} - u} \le 2L^2 - 2L^2 = 0
\end{align}\]

donde se ha usado la identidad del paralelogramo en (*).
*** Proyección ortogonal (de $H$ sobre $V$) label:claim:proy
A partir de ref:fact:dist podemos definir la proyección ortogonal como:

Se define como $p_V: H \rightarrow V$ dada por $p_V(u) = \argmin_{v\in V} \norm{u-v}$

**** Caracterización de $p_V$
Si $V$ es sub.cerrado de $H$ y $u\in H$ entonces $p_V(u)$ es el único elemento de $V$ verificando $u-p_V(u) \in V^\perp$

***** Demostración
La existencia es trivial a partir de label:claim:ortogonal y el hecho de que $p_V(u)$ minimiza la distancia de $u$ a $V$. 

\[u-p_V(u) \in V^\perp \Leftrightarrow \norm{u-p_V(u)} = \inf_{w\in V} \norm{u-p_V(u) - w}\]

Pero $\inf_{w\in V} \norm{u-p_V(u) - w} = \inf_{w\in V} \norm{u-w}$ y se cumple lo anterior por la definición de $p_V(u)$.

La unicidad viene dada por ref:fact:dist
*** Complemento ortogonal label:th:complemento
Decimos que $V^\perp$ es complemento ortogonal de $V$ en $H$ si $V\oplus V^\perp = H$

Nótese que si un espacio no es cerrado, no podríamos definir la proyección, y el siguiente teorema no sería válido.
 
**** Teorema del complemento ortogonal
Sea $V$ subespacio vectorial cerrado de $H$. Se cumple:

1. $p_V$ es la única aplicación lineal en $V^H$ verificando que $p_V \circ p_V = p_V$ y $Ker p_V = V^\perp$
2. $p_V$ es continua y $\opnorm{p_V}{H}{V} = 1$ si $V\neq \emptyset$
3. $i:V \oplus V^\perp \hookrightarrow H$ es isometría lineal.


Recordamos que la norma de operadores se define como $\opnorm{T}{V}{W} = \sup_{v\in V, \, \norm{v}_V = 1} \norm{T(v)}_W$, donde $\opspace{V}{W} = \{h:V\rightarrow W$ continua y lineal$\}$

***** Demostración
****** Primer punto
$p_V \circ p_V = p_V$ es trivial

$Ker p_V = V^\perp$, ya que dado $x\in H, p_V(x)=0$, tenemos $0 = p_V(x) = \argmin_{w\in V} \norm{w-x}$, sii $\norm{x} = \min_{w\in V} \norm{w-x}$. Por último: ref:claim:ortogonal nos dice que lo anterior se cumple sii $x\in V^\perp$

$p_V$ es lineal, porque por ref:claim:proy, como $\lambda u + \mu w - \lambda p_V(u) + \mu p_V(w) = \lambda (u-p_V(u)) + \mu (w-p_V(w)) \in V^\perp$, entonces $p_V(\lambda u + \mu w) = \lambda p_V(u) + \mu p_V(w)$.

Es la única aplicación lineal que cumple eso porque dada $f$ lineal verificando ambas condiciones, entonces:

\[f(f(x)-x) = f(f(x)) - f(x) \underset{f\circ f=f}{=} f(x) - f(x) = 0\]

Luego $f(x) - x \in V^\perp$ sii, por ref:claim:ortogonal $\norm{f(x)-x} = \inf_{w \in V} \norm{f(x) - x - w} \underset{f(x) \in V}{=} \inf_{w \in V} \norm{x-w}$, luego como por ser $V$ cerrado existe un único elemento que materializa la distancia, por label:fact:dist  entonces $f(x) = p_V(x)$
****** Segundo punto
Escribimos $u = u - p_V(u) + p_V(u)$, donde sabemos $u - p_V(u) \in V^\perp$, luego: 

\[\dotprod{u}{u-p_V(u)} = \norm{u}^2 - \dotprod{u}{p_V(u)} = \norm{u-p_V(u)}^2\]

Es decir:

\[\norm{u}^2 - \dotprod{u-p_V(u) + p_V(u)}{p_V(u)} = \norm{u}^2 - \norm{p_V(u)}^2 = \norm{u-p_V(u)}^2\]

Y se deduce $\norm{p_V(u)} \le \norm{u}$, y de aquí $\opnorm{p_V}{H}{V} \le 1$. Esto nos da continuidad.

Si $V \neq 0$, tomando $v\in V$, $p_V\left(\frac{v}{\norm{v}}\right) = \frac{v}{\norm{v}}$ y por tanto $\opnorm{p_V}{H}{V} = 1$
****** Tercer punto
Es claramente una función lineal, de kernel nulo, luego inyectiva, y es biyectiva, ya que dado $y\in H$, $i((y - p_V(y)) + p_V(y)) = y$, luego es isomorfismo lineal.

Es isometría por ser $\norm{u+v}_H^2 = ||u||^2 + ||v||^2 = \norm{u+v}_{V\oplus V^\perp}^2$, para $u\in V, v\in V^\perp$.




** Teorema de representación de Riesz-Fréchet
